### PR TITLE
HTTP 204 should have no body, not even Content-Length

### PR DESCRIPTION
**Pull request by kw217**
RFC7230 s3.3.2 says:

"A server MUST NOT send a Content-Length header field in any response with a status code of 1xx (Informational) or 204 (No Content)."

It also says that 304 is only allowed Content-Length in certain circumstances.

Currently Iron adds a `Content-Length: 0` header whenever there is no body. This is incorrect for 1xx and 204 responses and many 304 responses. This fix changes that behaviour, to strip any `Content-Length` header for 1xx and 204 responses, allow it but not add it for 304, and otherwise add it.

Edit: I discovered this because a Scala unmarshaller I'm using is refusing to parse 204 responses from Iron for this reason.

### CODE REVIEW

**Comment by robinst** [comment]
I think this would fix #528, right?

**Comment by kw217** [comment]
Yes, this fixes #528 .

**Comment by clarcharr** [comment]
Shouldn't this be included in Hyper, not Iron?

**Comment by kw217** [comment]
Arguably it should go in Hyper _as well_, but the code in Iron should do the right thing too. I think this is fixed in Hyper 0.11 anyway, but Iron is still using Hyper 0.10.

**Comment by phlmn** [comment]
Should be fixed with #523

**Comment by kw217** [comment]
Thanks, that's fine.

**Pull request closed without merging**
