### PR TITLE
Allow the Servers to be created in a generic way

### PR DESCRIPTION
**Pull request by samgiles**
This is really similar to @jimktrains's  PR - but with the suggestion addressed.

This is to support server side SNI with Iron - which I've implemented over here https://github.com/samgiles/foxbox/blob/https-support/src/http_server.rs#L75.  I plan on moving that into a nicer, and reusable module if this gets merged.

### CODE REVIEW

**Comment by samgiles** [comment]
Hey @reem, It would be awesome to get this feature merged, I'd be happy to make changes if you see any.

**Comment by untitaker** [comment]
I feel like an API like this would be less Java-esque:

    let iron = Iron::new(h);
    iron.protocol(Http);
    iron.addr(...);
    iron.hyper_server(...)  // The actual new functionality
    iron.listen();

Since the existing methods `http`, `https` and `listen_with` all consume `self`, they can modify the `Iron` instance at will.

**Comment by samgiles** [comment]
Hmm, nice idea, will take a look at doing that tomorrow, thanks.

**Comment by reem** [comment]
I agree with @untitaker, closing for now but feel free to make a new PR any time with the new plan.

**Pull request closed without merging**
