### PR TITLE
(feat) Stream the body of a Request as a Reader

### LINKED ISSUE #265: Allow streaming of the request body
cc #263

This is really a necessary improvement to support common operations like file upload and many other use cases.

### PR DESCRIPTION
**Pull request by reem**
This changes the behavior of Iron in a rather crucial way.
Instead of reading the entire body of an incoming Request into a
`Vec<u8>` at the creation time of a Request, the body is now
exposed as a Reader on the Request object and can be read on-demand
or not-at-all depending on its use.

Streaming is critical for uses such as file uploading, where loading
the entire request body into memory unconditionally is... bad.

The body is exposed as a mostly opaque `Body` type which implements
`Reader` and wraps hyper's `HttpReader<&'a mut (Reader + 'a)>`. The http
reader cannot currently be retrieved from a `Body`, but for testing
purposes `Body::new` can be used to construct a `Body` from an `HttpReader`.

Progress on #263
Fixes #265

### CODE REVIEW

**Comment by reem** [comment]
cc @s-panferov @cybergeek94

I had some free time so I just made the change. Thoughts on the approach? Do you think `Request` should implement `Reader` itself, or is the current isolation to the `body` field appropriate?

**Comment by cybergeek94** [comment]
I'm concerned that a naively written `BeforeMiddleware` would be able to opaquely invalidate a request by reading its body to EOF, since it is passed `&mut Request`, thus making the body unavailable to subsequent middleware and handlers. It's mostly the user's problem, but it also seems like something we could easily prevent in the API. 

Is there any use-case where `BeforeMiddleware` has to inspect the request body directly? That would break anyways with this change, since the ordering of the middleware affects how much of the body might have been read.

Perhaps `BeforeMiddleware` can get a `RequestInfo` struct that provides everything but the body, or separate the body from `Request` and pass it to `Handler` directly.

**Comment by s-panferov** [comment]
I think everything is good. If a middleware wants to read the entire body, it can provide the body or it parts as request extensions (with help of TypeMap).

**Comment by reem** [comment]
@cybergeek94 I think it would actually be the role of a Plugin to properly read the request body and transform it into whatever form a Handler can actually use and storing it the extensions, whether that's reading the whole thing and parsing it into JSON or parsing it using multipart or whatnot. It should be rare for the Handler to be responsible for dealing with a raw request body directly.

BeforeMiddleware used to fill this role, but the lazily-evaluated and cached nature of Plugins actually makes them ideal for dealing with this sort of one-shot data.

**Comment by reem** [comment]
Updated for #275, landing.

**Pull request merged**
