### PR TITLE
Improve conversion of iron::Url from/to url::Url

### PR DESCRIPTION
**Pull request by untitaker**
When I want to read data from the underlying `url::Url` (either because
it offers a richer API than Iron's URL for my usecases, or because I can
pass it directly into another API), I currently have two choices:

- `let url = request.url.into_generic_url().clone()`. This unnecessarily
  copies data.

- `let url = request.url.into_generic_url()`, which moves `request.url`,
  and do `request.url = iron::Url::from_generic_url(url)` when I'm done,
  to move the generic URL back into the request. This is unnecessarily
  verbose.

Both options are undesirable. Therefore `generic_url`.

I also have similar usecase for `generic_url_mut`. I have a middleware
that modifies a part of the request URL. Currently I'd have to do
similar tricks to do that.

### CODE REVIEW

**Comment by Hoverbear** [comment]
I guess it wouldn't make sense to use `Into` for this since you just want a pointer.

**Comment by untitaker** [comment]
I can imagine using Into instead of `into_generic_url` though. AsRef would probably be useful.

**Comment by Hoverbear** [comment]
Definitely. :)

**Comment by untitaker** [comment]
Would you say that implementing `From<url::Url>`, `Into<url::Url>` and `AsRef<url::Url>` is preferrable? Should I remove the redundant methods or leave those that are already in a stable release?

**Comment by Hoverbear** [comment]
If it already exists we should keep it -- People may depend on it.

But using existing, idiomatic methods such as `Into` etc would definitely be preferable for new code.

I, for one, prefer simple, familiar concepts over library-specific concepts. If you prefer this method it'd be awesome if we could have both ways.

**Comment by untitaker** [comment]
>But using existing, idiomatic methods such as Into etc would definitely be preferable for new functions.

I agree.

>it'd be awesome if we could have both ways.

I disagree, I don't think we should duplicate the API, and deprecate the existing methods.

I pushed a commit to show what I mean.

**Comment by untitaker** [comment]
We can't actually implement `From<url::Url>` because `from_generic_url` returns a `Result` and may fail. `TryFrom` is unfortunately not stable.

**Comment by Hoverbear** [comment]
@untitaker It looks very nice regardless. :)

**Comment by untitaker** [comment]
Do we agree though that `into_generic_url` should be deprecated? @reem Any comments?

**Comment by untitaker** [comment]
@reem I think this is ready to merge.

**Comment by untitaker** [comment]
I'll just go ahead...

**Pull request merged**
