### PR TITLE
(doc) use shields.io badges for consistency

### PR DESCRIPTION
**Pull request by DevoNoel**
It drives me a little nuts seeing badges with slight differences in style on a project's README.  
This PR uses [shields.io](http://shields.io) to style the Build and Crates.io badges more consistently.

### CODE REVIEW

**Comment by reem** [comment]
Sorry, but I really don't like how the crates.io badge from shields.io is orange. Maybe if you could find consistent styles with a crates.io badge that's green?

**Comment by DevoNoel** [comment]
@reem Alright, well how about just using Travis' .svg badge instead?

**Comment by reem** [comment]
@DevoNoel Looks great, thanks for fixing this!

**Comment by heibor** [comment]
I think use mio may be a good idear, it can bing us more performance.

**Pull request merged**
