### PR TITLE
Update to Hyper 0.10

### PR DESCRIPTION
**Pull request by sfackler**
r? @untitaker

### CODE REVIEW

**Comment by untitaker** [comment]
Thanks!

**Comment by sfackler** [comment]
Any idea when you could cut an 0.5 release with this?

**Comment by untitaker** [comment]
Done. By the way, Hyper's testsuite has been failing for a while now. What's up with that?

**Comment by sfackler** [comment]
Not sure - @seanmonstar?

**Comment by seanmonstar** [comment]
It's been wonky with openssl failing on the Mac box, and master hasn't seen any attention in a while. You can see the 0.10.x branch is passing here: https://travis-ci.org/hyperium/hyper/branches

The tokio branch was also passing yesterday, but I'm fiddling with the new released tokio crates today.

**Pull request merged**
