### PR TITLE
(docs): Add usage warning

### PR DESCRIPTION
**Pull request by s-panferov**
Let's warn people about current limitations and suggest to use a reverse proxy server.

Sorry if my language is incorrect. Feel free to say, I'll fix everything.

### CODE REVIEW

**Comment by reem** [comment]
While you might technically be right, I'm really don't *want* to put something like this in the README, it's bad for business, you know ;)

These are temporary limitations anyway, we are already thinking of better ways to distribute work over the thread pool to allow handling many more concurrent connections.

**Comment by s-panferov** [comment]
@reem nobody uses a sync web-server on mid/hi-load production without nginx, ha-proxy etc. It's just a reminder for newcomers. Maybe we can just remove the sentence about limitations and leave only the recommendation?

**Comment by reem** [comment]
Sure, if you craft it to be a little more positive ;)

**Comment by reem** [comment]
@s-panferov you still interested in landing this?

**Comment by reem** [comment]
closing due to inactivity but feel free to open another

**Pull request closed without merging**
