### PR TITLE
Move to new io/fs/path API and adjust to Hyper changes

### PR DESCRIPTION
**Pull request by panicbit**
These changes depend on hyperium/hyper#354

### CODE REVIEW

**Comment by panicbit** [comment]
There still needs to be some work.
Iron currently crashes when unwrapping the protocol (https://github.com/panicbit/iron/blob/a18db56fd6ffff94664a07784c1258fa827fa2b6/src/iron.rs#L147)

**Comment by panicbit** [comment]
The crash was caused by writing to a struct that moved away (See rust-lang/rust#21232)

**Comment by panicbit** [comment]
hyperium/hyper#354 is merged now, so this PR should build now

**Comment by s-panferov** [comment]
@reem could you merge this please to unblock iron clients?

**Comment by reem** [comment]
Taking a look right now.

**Comment by reem** [comment]
Looks great to me. Excellent work @panicbit.

**Pull request merged**
