### PR TITLE
(doc) Explain how to use Body as Read in its documentation

### PR DESCRIPTION
**Pull request by robinst**
It wasn't obvious to me how to do that and a note like this in the
documentation would have helped me.

### CODE REVIEW

**Comment by untitaker** [comment]
I'm unsure about this. I don't think the API docs are the right place for this.

**Comment by robinst** [comment]
It's one of the places where I looked for it. We can also put it in more than one place, that's not a bad thing for documentation. Where would you want to put it instead?

**Comment by untitaker** [comment]
To be honest I don't really understand wny Iron needs to document this. You can't pass `request.body` directly because that would destructure the request. You can't pass `&request.body` because you need to modify the body to be able to read it.

This is one of those things that naturally results out of how ownership works in Rust. I don't think Iron's API docs are the correct place to put this. I suppose we could have an example just for this though.

**Comment by robinst** [comment]
Sorry for keeping this open. I'll look into adding another example.

**Pull request closed without merging**
